DROP INDEX IF EXISTS idxMsg1;
DROP INDEX IF EXISTS idxMsg2;
DROP INDEX IF EXISTS idxStr1;
DROP TABLE IF EXISTS syncTopicStatus;
DROP TABLE IF EXISTS missingMessages;
DROP TABLE IF EXISTS storeNodeUnavailable;
